name: Lint

on:
  push:
    branches:
      - main
    paths:
      - '**/*.py'
      - '**/*.ipynb'
  pull_request:
    branches:
      - main
    paths:
      - '**/*.py'
      - '**/*.ipynb'
  workflow_dispatch:

jobs:
  lint:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install flake8 pylint nbqa

    - name: Get changed files
      id: changed-files
      run: |
        git fetch origin main
        CHANGED_FILES=$(git diff --name-only origin/main...HEAD | grep -E '\.py$|\.ipynb$' || true)
        echo "$CHANGED_FILES" > changed_files.txt
        echo "Changed files:"
        cat changed_files.txt

    - name: Run flake8 (incl. nbqa) on changed files
      run: |
        echo "Running flake8 checks..."
        status=0
        while IFS= read -r file; do
        if [[ "$file" == *.py ]]; then
        echo "flake8 on $file"
        flake8 "$file" || status=1
        elif [[ "$file" == *.ipynb ]]; then
        echo "nbqa flake8 on $file"
        nbqa flake8 "$file" || status=1
        fi
        done < changed_files.txt
        exit $status
